-- V2__enhance_outbox_message_for_dlq.sql
-- Add DLQ, retry, and audit columns to outbox_message

ALTER TABLE gepg.outbox_message
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'PENDING' NOT NULL,  -- PENDING, PUBLISHED, FAILED, DLQ
ADD COLUMN IF NOT EXISTS attempts INT DEFAULT 0 NOT NULL,
ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS last_error_message TEXT,
ADD COLUMN IF NOT EXISTS dlq_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS resolved_by VARCHAR(100),
ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS resolution_notes TEXT;
